openapi: "3.0.0"
info:
  version: 1.0.0
  title: My API
servers:
  - url: http://localhost:3000/api/v1
paths:
  /health:
    get:
      summary: Healthcheck of API
      tags:
        [ 'health' ]
      responses:
        '200':
          description: success
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /car:
    get:
      summary: Car Data
      tags:
        [ 'car' ]
      responses:
        '200':
          description: success
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Error"
components:
  schemas:
    Error:
      required:
        - message
      properties:
        message:
          type: string
